# Generated by Django 4.1.10 on 2023-07-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptor',
            new_name='description',
        ),
    ]
